Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BATCHNBACHUNK?createDatabaseIfNotExist=true
    username: root
    password: password
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

  batch:
    job:
      enabled: true
    initialize-schema: Always



## Docker helper info
# -> sudo docker start batch-mysql-db
# -> sudo docker container exec -it b3930d1af062 bash
# -> mysql -uroot -ppassword